stages:
    - deploy-images

deploy-images:
    image: docker:dind
    stage: deploy-images
    variables:
      DOCKERFILE: Dockerfile
      REGISTRY: registry.thejohnsons.site
      CNAME: docker-plex-openvpn
    script:
      - |
        export TAGS="git-commit-$CI_COMMIT_SHORT_SHA"
        if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
          export TAGS="$TAGS latest"
        fi
        if [[ ! -z "$CI_COMMIT_REF_NAME" ]]; then
          export TAGS="$TAGS $CI_COMMIT_REF_NAME"
        fi
        if [[ -n "$CI_COMMIT_TAG" ]]; then
          export TAGS="$TAGS $CI_COMMIT_TAG"
        fi

        export TAGS="$TAGS $(grep 'ARG PLEX_VERSION' $DOCKERFILE | awk -F'=' '{print $NF}')"
        export DOCKER_PASSWORD=$(echo -n $DOCKER_PASSWORD_BASE64 | base64 -d)

        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin $REGISTRY
        docker build --network=host -t $REGISTRY/$CNAME:_build -f $DOCKERFILE .
        for TAG in $TAGS; do
          echo "Tagging and pushing image \"$CNAME\" with \"$TAG\""
          docker tag $REGISTRY/$CNAME:_build $REGISTRY/$CNAME:$TAG
          for i in {1..3}; do
             docker push $REGISTRY/$CNAME:$TAG || true
          done
        done
